services:
  # Backend Web Service
  - type: web
    name: femguardbackenddeploy
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - fromGroup: pcos-secrets

envVarGroups:
  - name: pcos-secrets
    envVars:
      - key: DATABASE_URL
        value: # ADD_YOUR_NEON_DB_URL_HERE
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_KEY_ID
        value: # ADD_YOUR_RAZORPAY_KEY_ID_HERE
      - key: RAZORPAY_KEY_SECRET
        value: # ADD_YOUR_RAZORPAY_KEY_SECRET_HERE
      - key: FIREBASE_SERVER_KEY
        value: # ADD_YOUR_FIREBASE_KEY_HERE
      - key: EMAIL_USER
        value: # ADD_YOUR_EMAIL_USER_HERE
      - key: EMAIL_PASS
        value: # ADD_YOUR_EMAIL_PASS_HERE
